@startuml Alamofire-URLConvertible

' 1. URLConvertible
interface URLConvertible {
    asURL() -> URL
}

String ..|> URLConvertible
URL ..|> URLConvertible
URLComponents ..|> URLConvertible

' 2. URLRequestConvertible
interface URLRequestConvertible {
    asURLRequest() -> URLRequest
}

class URLRequest {
    + init(url: URLConvertible, method: HTTPMethod, headers: HTTPHeaders?)
}

struct RequestConvertible {
    ~ url: URLConvertible
    ~ method: HTTPMethod
    ~ parameters: Parameters?
    ~ encoding: ParameterEncoding
    ~ headers: HTTPHeaders?
    ~ requestModifier: RequestModifier?
}

struct RequestEncodableConvertible<Parameters: Encodable> {
    ~ url: URLConvertible
    ~ method: HTTPMethod
    ~ parameters: Parameters?
    ~ encoder: ParameterEncoder
    ~ headers: HTTPHeaders?
    ~ requestModifier: RequestModifier?
}

struct ParameterlessRequestConvertible {
    ~ url: URLConvertible
    ~ method: HTTPMethod
    ~ headers: HTTPHeaders?
    ~ requestModifier: RequestModifier?
}

left to right direction

URLRequest ..|> URLRequestConvertible
URLRequest --> URLConvertible: Denpendency
RequestConvertible ..|> URLRequestConvertible
RequestEncodableConvertible ..|> URLRequestConvertible
ParameterlessRequestConvertible ..|> URLRequestConvertible


@enduml